services:
  db:
    image: mariadb:latest
    container_name: sam_ti_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MARIADB_DATABASE: "sam_ti"
      MARIADB_USER: "sam_ti_user"
      MARIADB_PASSWORD: "sam_ti_pass"
      MARIADB_ROOT_PASSWORD: "root_pass"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  web:
    build: .
    container_name: sam_ti_web
    ports:
      - "2332:2332"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost,0.0.0.0,192.168.1.50,governanca.yuridevs.com.br"
      DJANGO_CSRF_TRUSTED_ORIGINS: "http://127.0.0.1,http://localhost,http://192.168.1.50:2332,https://governanca.yuridevs.com.br"
      DB_ENGINE: "django.db.backends.mysql"
      DB_NAME: "sam_ti"
      DB_USER: "sam_ti_user"
      DB_PASSWORD: "sam_ti_pass"
      DB_HOST: "db"
      DB_PORT: "3306"
    volumes:
      - .:/app

volumes:
  mariadb_data:
