# Generated by Django 6.0.3 on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avaliacao", "0004_planoacao_5w2h"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="planoacao",
                    name="custo_natureza",
                    field=models.CharField(
                        blank=True,
                        choices=[("CAPEX", "CAPEX"), ("OPEX", "OPEX")],
                        default="",
                        max_length=10,
                    ),
                ),
                migrations.AddField(
                    model_name="planoacao",
                    name="custo_recorrencia",
                    field=models.CharField(
                        choices=[("UNICO", "Único"), ("MENSAL", "Mensal"), ("ANUAL", "Anual")],
                        default="UNICO",
                        max_length=10,
                    ),
                ),
                migrations.AddField(
                    model_name="planoacao",
                    name="custo_valor",
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                migrations.CreateModel(
                    name="MetaIndicador",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("nome_indicador", models.CharField(max_length=180)),
                        ("unidade", models.CharField(blank=True, max_length=30)),
                        ("situacao_atual", models.CharField(blank=True, max_length=120)),
                        ("ano_conclusao", models.PositiveSmallIntegerField(blank=True, null=True)),
                        ("meta_conclusao", models.CharField(blank=True, max_length=120, db_column="meta_2029")),
                        ("observacoes", models.TextField(blank=True)),
                        ("criado_em", models.DateTimeField(auto_now_add=True)),
                        ("atualizado_em", models.DateTimeField(auto_now=True)),
                        (
                            "empresa",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="metas_indicadores",
                                to="avaliacao.empresa",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["nome_indicador"],
                    },
                ),
                migrations.CreateModel(
                    name="ObjetivoEstrategicoPDTI",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("objetivo", models.CharField(max_length=255)),
                        ("resultado_esperado", models.CharField(max_length=255, db_column="resultado_esperado_2029")),
                        ("ano", models.PositiveSmallIntegerField(blank=True, null=True)),
                        (
                            "empresa",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="objetivos_pdti",
                                to="avaliacao.empresa",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["id"],
                    },
                ),
                migrations.CreateModel(
                    name="PDTI",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("introducao", models.TextField(blank=True)),
                        ("objetivos_estrategicos_texto", models.TextField(blank=True)),
                        ("analise_situacional", models.TextField(blank=True)),
                        ("diagnostico_samti", models.TextField(blank=True)),
                        ("analise_de_riscos", models.TextField(blank=True)),
                        ("estrutura_governanca", models.TextField(blank=True)),
                        ("roadmap_evolucao", models.TextField(blank=True)),
                        ("visao_de_futuro", models.TextField(blank=True)),
                        ("conclusao", models.TextField(blank=True)),
                        ("criado_em", models.DateTimeField(auto_now_add=True)),
                        ("atualizado_em", models.DateTimeField(auto_now=True)),
                        (
                            "avaliacao",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="pdti",
                                to="avaliacao.avaliacao",
                            ),
                        ),
                    ],
                ),
            ],
        )
    ]
