# Generated by Django 6.0.3 on 2026-05-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0005_metas_pdti_custos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdti',
            name='objetivos_estrategicos_texto',
            field=models.TextField(blank=True, db_column='objetivos_estrategicos'),
        ),
    ]
