# Generated by Django 6.0.3 on 2026-05-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0009_objetivo_pdti_add_ano_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoacao',
            name='custo_natureza',
            field=models.CharField(blank=True, choices=[('CAPEX', 'CAPEX'), ('OPEX', 'OPEX'), ('ESTRATEGICO', 'Estratégico'), ('PREVENTIVO', 'Preventivo'), ('CORRETIVO', 'Corretivo'), ('MELHORIA_CONTINUA', 'Melhoria Contínua')], default='', max_length=20),
        ),
    ]
